name: Integration Test

on:
  workflow_run:
    workflows: ["Docker Image"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: GitHub SDK Sample
      uses: ./
